bugfix: import Warning
otherwise we get
```
TypeError: Warning() takes no keyword arguments
```
errors because it interpreted as
https://docs.python.org/3/library/exceptions.html#Warning

BTW: It was a bad idea to name the class same a as a Python built-in class.
TODO: Add tests that reveal such bugs